\ir orgs.sql
\ir permissions.sql
\ir owners.sql
\ir teams.sql
\ir repos.sql
\ir services.sql
\ir builds.sql
\ir apps.sql
\ir releases.sql
\ir members.sql
\ir tokens.sql
\ir plans.sql
\ir subscriptions.sql
