CREATE TABLE services(
  uuid                       uuid default uuid_generate_v4() primary key,
  repo_uuid                  uuid references repos on delete cascade not null,
  alias                      alias unique,
  pull_url                   url,
  topics                     citext[],
  description                text
);
COMMENT on column services.alias is 'The namespace reservation for the container';
COMMENT on column services.pull_url is 'Address where the container can be pulled from.';
COMMENT on column services.topics is 'GitHub repository topics for searching services.';

CREATE INDEX services_repo_uuid_fk on services (repo_uuid);

CREATE TYPE service_state as enum('DEVELOPMENT', 'PRERELEASE', 'BETA', 'STABLE', 'ARCHIVED');

CREATE TABLE service_tags(
  tag                        citext not null,
  service_uuid               uuid references services on delete cascade not null,
  state                      service_state not null,
  configuration              jsonb,
  readme                     text,
  primary key (tag, service_uuid)
);

COMMENT on column service_tags.tag is 'The verion identifier. E.g., latest or v1.2';
COMMENT on column service_tags.configuration is 'The post processing of the microservice.yml file.';
COMMENT on column service_tags.readme is 'The readme content (first generated by the repository README).';
