query GetAlias($owner: Username! $repo: Username! $tag: String!){
  allOwners(condition: {username: $owner}, first: 1){
    nodes{
      repos(condition: {name: $repo}, first: 1){
        nodes{
          services(first:1){
            nodes{
              pullUrl
              serviceTags(condition: {tag: $tag}, first: 1){
                nodes{
                 configuration
                }
              }
            }
          }
        }
      }
    }
  }
}
